### ISSUE TITLE
CAN2 ISRs do not work on F7

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#11]
This is an issue that needs to be addressed to make an efficient router. Something to do with the master-slave relationship between CAN1 and CAN2 on F7

**Comment by caljay98** [comment]
I think this is because I didnt enable interrupts in the CubeIDE setup. Oops

**Comment by caljay98** [comment]
Yep, Calvin is stupid. The ISRs were not enabled

**Comment by hocally** [comment]
How she goes sometimes
