### ISSUE TITLE
Add support for fixed-point conversion once below application layer

### ISSUE THREAD

**Issue by hocally** [gopher-motorsports/gophercan-lib#15]
If the application is using a float, convert it to fixed-point before sending and convert back to float on the other side for the other application

**Comment by hocally** [comment]
This might be a waste of time if floats can be easily fixed

**Comment by hocally** [comment]
@caljay98 Is this relevant anymore per your float troubleshooting?

**Comment by caljay98** [comment]
Nope, floats are fixed making this not needed
