### ISSUE TITLE
Use CSV files for GopherCAN message mapping

### ISSUE THREAD

**Issue by hocally** [gopher-motorsports/gophercan-lib#3]
Just an idea, makes it easy to see diffs in Git when you make a change. Down the road, we can look at using a different file format altogether (DBC).
If there are any Excel functions used in the file, might be nice to convert them to python scripts that act on the csv for added maintainability

**Comment by caljay98** [comment]
This is more up in the air now, possibly .ymal, so closing this issue as there are more current issues that explain the feature better
