### ISSUE TITLE
Add support for STM32F4 MCUs

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#50]
This should just be adding another build option, all other features are the same as the F7

**Comment by hocally** [comment]
@caljay98 at some point remind me to show you the STM build system default defines, there are some -D flags for each MCU variant so you might be able to leverage some existing macros

**Comment by hocally** [comment]
Random example
https://github.com/gopher-motorsports/aerodynamic-control-module/blob/79b84723253242c545d01de28146224b9a127c6d/Debug/Core/Src/subdir.mk#L48
![image](https://user-images.githubusercontent.com/21182349/114779201-a9ecfc80-9d2a-11eb-8443-b8588f7d196c.png)

**Comment by caljay98** [comment]
I am pretty sure this is already good to go
