### ISSUE TITLE
Finish the go4-22c.yaml CAN definition file

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#57]
Some of the old fields will need to be updated with new values based on the updated auto gen

**Comment by caljay98** [comment]
Did it bitch

**Comment by HansBakken** [comment]
Please link the relevant PR or branch where this issue is complete and provide verification evidence. Thanks!!!!!!

**Comment by caljay98** [comment]
Don't be too harsh on me, I'm just an intern
