### ISSUE TITLE
Look into the GopherCAN_config.h file and consider how much is needed and how much can be removed

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#71]
There are lots of things in the config that may not be needed anymore. Remove unnecessary things to reduce confusion in the library.

**Comment by olale013** [comment]
A lot of CAN related HAL functions are wrapped by "#if TARGET == F7XX || TARGET == F4XX". Are any F0 boards actually used? If not, we could remove a lot of the mess.
