### ISSUE TITLE
Change the gophercannon folder to something better

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#74]

**Comment by olale013** [comment]
Could you elaborate? We can remove most of the stuff in the folder, but will still have ~5 files. Probably better to leave them in their own folder.

Related: is it safe to remove the config_outdated / example_files / other_files folders? Some of it is irrelevant with the new changes. Some of it is documentation which I think would be better in the Drive.

**Comment by caljay98** [comment]
I just wanted the name changed. It came up in a talk with Ben that the name "gophercannon" doesn't mean anything to someone who has never read it before. Something like "code_auto_gen" is much more descriptive.

Fun fact: it comes from the Tesla auto gen names, jcannon

**Comment by caljay98** [comment]
And example and such should be moved to the wiki for sure. Delete things that are not relevant Anymore
