### ISSUE TITLE
Make finding the group a parameter is in more efficient for encoding and decoding

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#80]
Right now the code must generate what params are in a group and how long they are each time they are encoded and decoded. It would be more efficient to store that information in static memory with the group

**Comment by olale013** [comment]
Add the following members to the `CAN_INFO_STRUCT`:
```
U8 START;
U8 LENGTH;
```

New group struct:
```
typedef struct
{
    U16 group_id;
    GCAN_PARAM_ID param_ids[8];
} PARAM_GROUP;
```

Network generator should verify that the parameters don't overlap and fit in 8 byte field.

Current version of GopherCAN will not support parameters belonging to multiple groups. For the future, this would require parameter size and length to be properties of the group, not the parameter. And a way to identify which group should be sent when send_parameter is called.

**Comment by olale013** [comment]
If `group.param_ids` looks like this:
`{U8_TESTER_ID, U16_TESTER_ID, EMPTY, U32_TESTER_ID, EMPTY, EMPTY, EMPTY, EMPTY, }`

The `START` property is unnecessary. Iterate through `param_ids`, get `LENGTH` from the appropriate param, fill that many bytes, move to the next ID. Skip empty IDs. Basically just removes the counting process.

Maybe call `LENGTH` `ENC_SIZE` instead to reduce confusion between `LENGTH` and `SIZE`, and to match `ENC`.

**Comment by caljay98** [comment]
That sounds good with the ENC_SIZE name. The only thing I worry about with removing the start is we sometimes want to have gaps in the message (non-gcan modules sometimes have it to line up bytes nicely). Is this still supported?

**Comment by olale013** [comment]
The position in param_ids[] is taken as the starting point. EMPTY_IDs will be skipped so yes, gaps are still possible. I think this should work:

```
for (U8 i = 0; i < CAN_DATA_BYTES; i++)
{
    GCAN_PARAM_ID id = group->param_ids[i];
    if (id == EMPTY_ID) continue;

    // check to make sure this is a good id. We are down bad if it is not
    if (id < EMPTY_ID || id >= NUM_OF_PARAMETERS) return BAD_PARAMETER_ID;

    // add this parameter's data to the message
    CAN_INFO_STRUCT* param = (CAN_INFO_STRUCT*) PARAMETERS[id];
    err = encode_parameter(param, message.data, i, param->ENC_SIZE);
    if (err) return err;
}
```

This assumes the ENC_SIZE of the parameters and the layout of param_ids[] is valid. If not stuff will break/overlap.

**Comment by caljay98** [comment]
Looks good to me
