### ISSUE TITLE
Issue when encoding and decoding negative float datatypes

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/gophercan-lib#83]
If a float gets encoded to a value below zero, it just gets truncated to 0 when it is cased to a U64. This is an issue as the MoTeC ECU frequently sends negative values that are stored in the library as a float, usually as a S16 on the bus with some scaler. A potential solution would be to read off the bus as a S16 and convert that to a float

**Comment by olale013** [comment]
How do we know if a float was meant to be signed or not on the bus? e.g. should we pull `10000001` from a message as 129 or -127?

**Comment by caljay98** [comment]
I have been thinking, and I think we should always assume signed integers, as thats what both the ECU and the Inverter do. I also think it is not worth worrying what we should do in the case of 3byte messages, as I cant really see a reason for doing that
